{include file='components/header_new.tpl' hide_submenu='1'}

<div align="center">
    <div class="content_rules_block">
        <div class="contest_rules_header">ShareBloc Content Marketing Nation Contest Rules</div>

        <p>NO PURCHASE NECESSARY TO ENTER OR WIN. MAKING A PURCHASE DOES NOT INCREASE YOUR CHANCES OF WINNING. ALL FEDERAL, STATE, LOCAL AND MUNICIPAL LAWS AND REGULATIONS APPLY. VOID WHERE PROHIBITED. This Contest is sponsored by VendorStack dba ShareBloc.com, Inc. 2501 300 Berry Street #1003 San Francisco, CA 94158 (the "Company").</p>

        <p>Enter the Contest ("Contest") as directed on the Contest entry page and you could win a prize (the "Prize") as specified on the Contest entry page. Prizes are not assignable or transferable. No person (the "Entrant") is eligible to win more than the number of prizes as specified on the Contest entry page. The promotion will run during the time period as specified on the Contest entry page (the "Contest Period"). NO PURCHASE NECESSARY. Just follow the Official Contest Rules below for all the details. Void where prohibited. Company reserves the right to modify these Official Contest Rules in any way or at any time. Company reserves the right, in their sole discretion, to cancel or suspend this Contest should viruses, bugs or other causes beyond their control corrupt the administration, security or proper functioning of the Contest.</p>

        <p><div class="legal_subheader">Eligibility</div></p>
        This Contest is limited to residents of the United States (excluding Puerto Rico) who at the time of entry have reached the age of 18 (eighteen) and have entered valid and verifiable information upon entry.

        <p>Employees, agents, successors, and assignees of the Company as well as family and household members of same, are ineligible to participate in the Contest and will be ineligible for any prize covered in these Official Contest Rules. Entrants acknowledge that Company is not liable for reimbursement of any prize otherwise payable to Contest Entrants who are in violation of this provision. Residents of jurisdictions where this Contest is prohibited by law or subject to other procedures with which ShareBloc.com may not have complied are ineligible for any prize covered herein.</p>

        <p><div class="legal_subheader">Entry</div></p>
        Enter online during the time period as specified on the Contest entry page (the "Promotion Period"). Each Entrant must enter in the manner as described on the Contest entry page. Any invalid or incorrect information will constitute cause for disqualification and Entrant will be ineligible to claim a prize. All entries become the property of the Company and will not be acknowledged or returned. Incomplete entries are void. Entries which are completed or entered by other than human means or otherwise not in compliance with these Official Contest Rules will be disqualified and the Entrant shall be ineligible for future participation.

        <p><div class="legal_subheader">Contest Submissions</div></p>
        By submitting the Contest Submission(s) ("Submission"), Entrant hereby grants Company a worldwide, non-exclusive, royalty-free, fully paid, sublicenseable and transferable     license to use, reproduce, display, and create any derivative works of the Submission in perpetuity, including but not limited to editorial content regarding the Submission, and that Company shall have the right to publish the Submission in any media format, including all social medial channels, now known or hereafter devised (including any reproduction or derivative work) and use in perpetuity the entrant's name and likeness for any lawful purpose, including promotional purposes, without further compensation. By entering the Contest, Entrant represents that entrant created the Submission for his/her entry into this Contest. Entrant forever waives any rights of privacy, intellectual property rights, and any other legal or moral rights that may preclude Company's use of his/her Contest Entry, or require Entrant's permission for Company to use his/her Contest Entry for any purpose, and agree to never sue or assert any claim against Company for its use of his/her Contest Entry.

        <p><div class="legal_subheader">Content Restrictions</div></p>
        Entrant may not submit or post anything that is offensive or violates any third party's rights. For example, your Contest Entry must not contain or reference any of the following:

        <div class="legal_subcontent">

            <p>&#8226; Nudity or lewd, vulgar, indecent or obscene images (as determined in Company's sole discretion);contemplated by the Service and this Agreement, and each such person has released you from any liability that may arise in relation to such use.</p>

            <p>&#8226; Material that violates or infringes another's rights, including but not limited to privacy, publicity or intellectual property rights;</p>

            <p>&#8226; Material that is protected by trade secret or otherwise subject to a third party's proprietary rights, including privacy and publicity rights, unless Entrant is the owner of such rights or have permission from their rightful owner to post the material;</p>

            <p>&#8226; Depiction of defamatory statements (including but not limited to words or symbols that are widely considered offensive to individuals of a certain race, ethnicity, religion, sexual orientation or socioeconomic group);</p>

            <p>&#8226; Material that is unlawful, in violation of or contrary to the laws or regulations in any country, state or province where the Contest Entry is created.</p>

        </div>

        Company may, in its sole discretion, disqualify any Contest Entry that does not comply with these Content Restrictions or that Company otherwise deems to be inappropriate in its sole discretion. In the event of disqualification, the Contest Entry will not be judged or considered for a prize.

        <p><div class="legal_subheader">Prizes</div></p>
        The prize varies by Contest and is governed by the prize specified on the Contest entry page. The winner will receive the prize indicated on the Contest entry page. No Entrant is eligible to win more than the number of prizes as described on the Contest entry page during the Promotion Period. The total value of all prizes awarded under this Contest shall not exceed the dollar amount as specified on the Contest entry page. In the event that a prize quantity is not specified on the Contest entry page, there shall be 1 (one) prize awarded. In the event that a prize value is not specified on the Contest entry page, the total value of all prizes awarded under the Contest shall not be greater than $100.00 (one-hundred dollars USD). Company reserves the right to substitute the prize or prize items with similar items of equal or greater value.

        <p><div class="legal_subheader">Selection of Winners</div></p>
        Following the end of the Contest, the person who submitted the post with the most number of votes will be the winner. The total number of winners selected varies by Contest and is governed by the number specified on the Contest entry page. In the event that the number of winners is not specified on the Contest entry page, the number of winners shall be one (1). Winner(s) shall be selected from all eligible valid entries received during the Promotion Period by the Company. Company reserves the right to interview and feature any and all winners on Company's website at www.sharebloc.com and on Company's social media channels.

        <p>The number of eligible entries received determines the odds of winning. In the event of a dispute regarding the identity of the person submitting the entry, the entry will be deemed to be submitted by the person in whose name appears on the User Profile of the person who submitted the post. The Contest will be conducted under the supervision of the Company. The decisions of the Company are final and binding in all matters relating to this Contest. The Company will notify the winner(s) via email or social media. Winner(s) must claim their prize within 5 (five) business days after the date of notification of such prize. A Contest winner's failure to respond to the prize notification within the specified 5 (five) business days will be considered such Contest winner's forfeiture of the prize and an alternate winner may be selected from the pool of eligible entries. If an Entrant is found to be ineligible, an alternate winner may also be selected from the pool of eligible entries. Company reserves the right to ship prizes directly to the mailing address provided by the winner(s). Each entry submitted in response to the Contest and in accordance with the rules will constitute an official entry. All Entrants agree to abide by these Official Contest Rules. All entries become the property of the Company.</p>

        <p>In no event shall the Company be obligated to award more prizes than the number of prizes stated in these Official Contest Rules. No substitutions by winner(s) are permitted. Winner(s) shall be responsible and liable for all federal, state and local taxes on the value of their prize. To receive a complete list of winners or a copy of the Official Contest Rules, send a self-addressed stamped envelope to ShareBloc.com, Inc., 300 Berry Street #1003 San Francisco, CA 94158. Specify winner's list or rules on your request.</p>

        <p><div class="legal_subheader">Privacy Notice</div></p>
        Any information Entrants provide to the Company will be used to communicate with Entrants in relation to this Contest. Company may also share this information with advertisers to contact Entrants at a future date about new products and services Company believes Entrants will find of interest. For complete details, see Company's Privacy Policy.

        <p><div class="legal_subheader">General Conditions and Releases</div></p>
        No purchase necessary. A purchase will not increase your odds of winning. Void wherever prohibited or restricted by law.

        <p>By entering the Contest, Entrants agree to abide by all terms of the Official Contest Rules and the decisions of the Company, made in its sole discretion, which shall be final. Company reserves the right to terminate the Contest at any time and for any reason prior to the stated expiration date. Company is not responsible for incorrect, or inaccurate transcription of entry information, for any human error, technical malfunctions, lost/delayed data transmission, omission, interruption, deletion, defect, theft or destruction or unauthorized access to, or alteration of, entries, for line failures or other failures of any telephone network, server, providers, computer equipment, software or any combination thereof, for inability to access any web site or online service or any other error or malfunction, or for late, lost, illegible, misdirected or incomplete entries which may limit an Entrant's ability to participate. Company is not responsible for any injury or damage to participants or any other person's computer related to or resulting from participation or downloading any materials in this Contest. Company is not responsible for technical, hardware or software failures of any kind, lost or unavailable network connections or failed, incomplete, garbled or delayed software transmissions or any mistake in the printing of these rules or failure to make e-mail notifications, if any, to Entrants. CAUTION: ANY ATTEMPT BY ANY PERSON TO DELIBERATELY DAMAGE ANY WEB SITE OR UNDERMINE LEGITIMATE OPERATION OF THE CONTEST IS A VIOLATION OF CRIMINAL AND CIVIL LAWS AND SHOULD SUCH AN ATTEMPT BE MADE, COMPANY RESERVES THE RIGHT TO SEEK DAMAGES FROM ANY SUCH PERSON TO THE FULLEST EXTENT PERMITTED BY LAW.</p>

        <p>Incorrect or inaccurate information supplied upon entry will cause subsequent entries to be void and ineligible for a prize.</p>

        <p>Entry materials that have been tampered with or altered are void. No copies, facsimiles or reproductions of online entry form will be accepted. Mechanically duplicated, mass machine printed entries, or entries not otherwise in compliance with the Official Contest Rules will be disqualified. No more than the advertised number of prizes will be awarded.</p>

        <p>If for any reason the Internet portion of the Contest is not capable of running as planned, including infection by computer virus, bugs, tampering, unauthorized intervention, fraud, technical failures or any other causes beyond the control of Company which corrupt or affect the administration, security, fairness, integrity or proper conduct of this Contest, Company reserves the right at its sole discretion to disqualify any individual who tampers with the entry process, and to cancel, terminate, modify or suspend the Contest.</p>

        <p>If a dispute arises regarding who submitted a post, the post will be deemed submitted by the person in whose name the post was made.</p>

        <p>No substitution or transfer of prizes permitted by winner(s). Taxes, if any, are the winners' responsibility. If the prize is not a cash prize, Company may refuse delivery of prize until such time as the winner(s) provide Company with the monies necessary to meet applicable tax withholding requirements. The prize is paid only to the winner during his/her lifetime and cannot be assigned, transferred or inherited by heirs or any other person.</p>

        <p>Winner(s), by acceptance of a prize, agree to release the Company, its parent, subsidiary and affiliated businesses and each of their officers, directors, shareholders, employees, advisors, assignees, agents, licensees, representatives and any other person or entity associated with this Contest from any and all liability claims or actions of any kind whatsoever for injuries, damage or losses to persons and property which may be sustained in connection with the receipt, enjoyment, ownership or use of the prize. The Company expressly disclaims any responsibility or liability for injury or loss to any person or property relating to the delivery and/or subsequent use of any prize awarded.</p>

        <p>The laws of the United States govern this promotion. All issues and questions concerning the construction, validity, interpretation and enforceability of these Official Contest Rules, or the rights and obligations of Entrant and Company in connection with the Contest, shall be governed by, and construed in accordance with the laws of the State of California, without giving effect to any choice of law or conflict of law rules or provisions (whether of the State of California or any other jurisdiction), that would cause the application of the laws of any jurisdiction other than the State of California.</p>

        <p>Each Entrant agrees that: (a) any and all disputes, claims, and causes of action arising out of or in connection with this Contest, or any prizes awarded, shall be resolved individually, without resort to any form of class action; (b) if the parties are unable to resolve their dispute amicably, it shall be resolved by arbitration; (c) any and all claims, judgments, and awards shall be limited to actual out-of-pocket costs incurred, including costs associated with entering this Contest, but in no event and under no circumstances will Entrant be permitted to obtain awards for attorneys' fees; and (d) Entrant hereby waives all rights to claim, punitive, incidental, and consequential damages, and any other damages, other than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased.</p>
    </div>
</div>
{include file='components/js_common.tpl'}
{include file='components/footer_new.tpl'}